새로운 피그마 디자인에 맞게 로그인, 프로필 편집 화면을 재구성 했습니다
flutter-seoul/flutter_boilerplate pull request #11
Opened 2022-10-21 09:59 UTC by nain93

- [x] 다크모드를 적용해서 모드에 맞게 이미지, 색상을 변경 했습니다. ( 앱 내부, 시스템 )
- [x] 프로필 사진을 추가 앱 갤러리에서 추가 할 수 있고 변경 할 수 있습니다. 
- [ ] 스플래시 화면, 앱 아이콘 변경 작업이 아직 안 되어있습니다 
( flutter_native_splash 패키지상에서 이미지 변경시 ios는 로고가 2번 뜨는 이슈가있고 안드로이드12에서는 화면이 나오지않아 해결중입니다 )

<div>
<img src="https://user-images.githubusercontent.com/73378472/197167044-42b5d010-ce49-452b-88a9-9be2435fdf17.gif" width="200">
<img src="https://user-images.githubusercontent.com/73378472/197167489-e0f2d728-e2f5-4d63-8d3c-1754932ae6fc.gif" width="200">
</div>

2022-10-21 11:36 UTC, hyochan commented
컨플릭트 해결해주시고 다시 날려주시면 좋을 것 같습니다 ~!

2022-10-21 11:44 UTC, hyochan requested changes
컨플릭트 해결해주시고 다시 날려주시면 좋을 것 같습니다 ~!

<img width="600" alt="Screen Shot 2022-10-21 at 8 36 19 PM" src="https://user-images.githubusercontent.com/27461460/197187170-1a46374b-5770-4c4e-bd12-9f2242b75060.png">

2022-10-22 05:25 UTC, hyochan requested changes
소소한 리뷰만 드렸습니다.

그리고 다음 부터는 rebase를 쳐주시면 좋을 것 같습니다.

https://www.youtube.com/watch?v=tX2qn2x6v48&t=906s

2022-10-22 05:25 UTC, hyochan commented on lib/screens/edit_profile.dart
> +                      ),
`NormalTextField` => `EditText` 로 변경하면 어떨까요?

2022-10-22 05:25 UTC, hyochan commented on lib/screens/home.dart
> +    }
`if` & `else`문 말고 `if` return문으로 바꿔주시면 좋을 것 같아요.
https://www.digitalocean.com/community/posts/5-tips-to-write-better-conditionals-in-javascript

2022-10-22 05:25 UTC, hyochan commented on lib/screens/home.dart
> +                        "Flutter Seoul",
Localization을 적용하면 어떨까요.
`Flutter Seoul`, `플러터 서울`

2022-10-22 05:25 UTC, hyochan commented on lib/screens/home.dart
> +                        )),
반복되는 코드는 데이터로 매핑해주면 좋을 것 같아요.

예시:
```
["email", "password"].map((text) { return Container...}).toList()
```

2022-10-22 05:25 UTC, hyochan commented on lib/screens/home.dart
> +                    SolidButton(
`SeoulButton`으로 바꾸면 좋을 것 같아요.

2022-10-22 05:25 UTC, hyochan commented on lib/main.dart
> +          name: '/editProfile',
이런 문자열은 `edit_profile`, `lower_snakecase`로 해주는게 좋을 것 같아요.

https://dooboo-ui.dooboolab.com/?path=/docs/contributing-contributing--page
위 페이지에서 아래 내용 참고 하시면 되세요.
<img width="939" alt="Screen Shot 2022-10-22 at 2 21 42 PM" src="https://user-images.githubusercontent.com/27461460/197321963-3c1b13e7-1bcc-4d30-8dbd-eb3db9e60280.png">

2022-10-22 05:25 UTC, hyochan commented
CI fail 난 것도 확인해주세요~!

2022-10-23 06:07 UTC, nain93 commented
홈화면이 원래 카운트 증가시키는 기능 화면 이었는데, 변경되어서 home_test 테스트 코드 주석처리 해놨습니다
@hyochan

2022-10-23 09:09 UTC, hyochan commented on lib/screens/home.dart
> +                    }).toList()),
https://github.com/flutter-seoul/flutter_boilerplate/pull/11#discussion_r1002352519

이거 의도를 잘못 파악하신 것 같아요!.

React처럼 object를 잘 정의하셔서 컴포넌트 하나로 만들어보시라는 말이었습니다.
다시 해보시면 좋을 것 같아요!

2022-10-25 08:32 UTC, hyochan commented on lib/screens/home.dart
> +                          margin: const EdgeInsets.only(bottom: 15),
사이즈만 필요할 떄는 `Container` 말고 `SizedBox`를 사용해주세요.
더불어 이것까지 `EditText` 안에 넣으면 좋을 것 같아요.

`dooboo-ui`에 [UI 컴포넌트를 만드는 법](https://dooboo-ui.dooboolab.com/?path=/docs/contributing-contributing--page)에 대해 한번 읽어보시면 좋을 것 같습니다.

2022-10-25 08:32 UTC, hyochan approved these changes
우선 한번 머지 하겠습니다.
고생하셨습니다 👍

2022-10-25 08:33 UTC, merged